os: Visual Studio 2015

version: 0.0.1-{branch}-{build}

install:
- dotnet restore

configuration: Release
platform: Any CPU

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal

after_build:
- ps: >-
    dotnet pack 'src/GeoHash.Net' --no-build -c $Env:CONFIGURATION --version-suffix $Env:APPVEYOR_BUILD_NUMBER

artifacts:
- path: 'src/GeoHash.Net/**/*.nupkg' 
  name: Nuget

test_script:
 - ps: >-
    dotnet test 'test/GeoHash.Net.Tests'