# configuration for "master" branch
-
  branches:
    only:
      - master

   os: Visual Studio 2015		
   version: 0.0.1-{branch}-{build}
   install:
   - dotnet restore
   
   configuration: Release
   platform: Any CPU
   
   build:
     publish_nuget: true
     publish_nuget_symbols: true
     include_nuget_references: true
     verbosity: minimal
   
   after_build:
   - ps: >-
       dotnet pack 'src/GeoHash.Net' --no-build -c $Env:CONFIGURATION --version-suffix $Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_NUMBER
   
   artifacts:
   - path: 'src/GeoHash.Net/**/*.nupkg' 
     name: Nuget
   
   test_script:
    - ps: >-
       dotnet test 'test/GeoHash.Net.Tests'

# "fall back" configuration for all other branches
# no "branches" section defined
# do not deploy at all
-
  os: Visual Studio 2015		
  version: 0.0.1-{branch}-{build}
  install:
  - dotnet restore
  
  configuration: Release
  platform: Any CPU
  
  build:
    publish_nuget: true
    publish_nuget_symbols: true
    include_nuget_references: true
    verbosity: minimal
  
  after_build:
  - ps: >-
      dotnet pack 'src/GeoHash.Net' --no-build -c $Env:CONFIGURATION --version-suffix $Env:APPVEYOR_REPO_BRANCH-$Env:APPVEYOR_BUILD_NUMBER
  
  artifacts:
  - path: 'src/GeoHash.Net/**/*.nupkg' 
    name: Nuget
  
  test_script:
   - ps: >-
      dotnet test 'test/GeoHash.Net.Tests'