os: Visual Studio 2015

version: 0.0.{build}

install:
- dotnet restore

configuration: Release
platform: Any CPU

build:
  publish_nuget: true
  publish_nuget_symbols: true
  include_nuget_references: true
  verbosity: minimal
artifacts:
- path: '**\*.nupkg' 
  name: Nuget